package no.uio.ifi.in2000.prosjekt.ui.commonUIUtils

import no.uio.ifi.in2000.prosjekt.model.InfoObjects
import no.uio.ifi.in2000.prosjekt.R

data class InfoUIState(
    val listOfInfo : List<InfoObjects> = listOf(
        InfoObjects("0", "Hvorfor varierer badetemperaturen?", R.drawable.thermometer, "https://havvarsel.no/info/havet.jpg",       "Sjøens overflatetemperatur – eller badetemperaturen – er hovedsakelig styrt av det lokale været. Det er til stor del solen som varmer opp badevannet om sommeren, mens vinden kan ødelegge gode badetemperaturer. \n\n Hvis dere har hatt fint vær med mye sol og har oppnådd gode badetemperaturer, vil sterk vind kunne blande overflatevannet med det kaldere vannet som ligger under. Hvis det i tillegg blir fralandsvind, så vil det varme overflatevannet drive vekk og bli erstattet med kaldere vann nedenfra. Hvis det er stor forskjell i temperaturen mellom overflatevannet og det som ligger 10–20 meter dypere, vil vindens påvirkning kunne endre badetemperaturen drastisk på veldig få timer. \n\n Sjøvann som kommer drivende fra nære eller fjerne områder vil også påvirke badetemperaturen lokalt, men ikke i så stor grad som solstråling, vind og lufttemperatur."),
        InfoObjects("1", "Lær mer om vind", R.drawable.wind,"https://havvarsel.no/info/vind.jpg",       "Årsaken til vind er forskjeller i lufttrykk, som igjen skyldes temperaturforskjeller over kloden eller lokale effekter av nedkjøling eller oppvarming av luftmasser. Vind blåser i utgangspunktet fra høytrykk mot lavtrykk, men jordrotasjonen gjør at vinden går med høyt trykk til høyre og lavt trykk til venstre (på den nordlige halvkule). Jo større trykkforskjeller, jo sterkere vind.\n\nVindretningen ved havoverflaten skyldes et komplisert samspill mellom flere faktorer. Svake vinder blåser ofte parallelt med kystlinjer, fjorder og dalsider, mens større og sterkere vindsystemer kan presse luft på tvers av dette.\n\nSolgangsvind (‘solgangsbris’) er et godt eksempel på vind som varierer med tiden. Siden sjø kan ta opp i seg mer varme enn land, vil temperaturen på land variere sterkest i takt med solen. På ettermiddagen blir det varmest over land, og luften der varmes opp, stiger, og erstattes av luft fra sjøen – pålandsvind. Om natten skjer som regel det motsatte og vi får en svak fralandsvind. Jordens rotasjon gjør at vinden ikke nødvendigvis går rett på eller fra land, men bøyes av mot høyre og blir til vind langs land.\n\nSterkere vinder kommer med de store lavtrykksystemene når disse møter landet vårt. De kan variere fra helt ufarlige vindsystemer til orkaner. Forskjellene er store mellom fjord og kyst. På utsatte steder som Lista, Kråkenes, Nordøyan og Vardø opptrer vindstyrke liten kuling eller mer nesten 10 ganger så ofte som i fjordene. Liten storm eller mer er svært sjeldent i skjermede områder.\n\nVind er og har alltid vært avgjørende for all aktivitet på og nær sjøen. Både som drivkraft og energikilde, eller som en ødeleggende kraft. Alle som skal på eller i sjøen bør være spesielt oppmerksom på vinden og hvordan den blir varslet."),
        InfoObjects("2", "Lær mer om strøm", R.drawable.waves,"https://havvarsel.no/info/strom.jpg",       "Vinden drar på vannmassene, og jo sterkere den er, jo kraftigere vil strømmen bli. I trange fjorder og sund samles luftmassene, og vinden blir forsterket – strømmen likeså.\n\nTidevannet beveger seg som en veldig lang bølge langs kysten vår (ca. 12 timer mellom høyvann og lavvann). På bølgens vei fra sør til nord strømmer vann inn og ut av fjorder og presses gjennom sund og streder. Noen steder langs norskekysten, f.eks. Saltstraumen og Moskstraumen, kan tidevannsstrømmene bli så sterke som 10–20 meter per sekund.\n\nElver bidrar med ferskvann som legger seg i overflaten siden det er lett, og derfor strømmer vannet fra elven bort fra elvemunningen. Jo mer elveavrenning, jo sterkere strømmer ved elvemunninger og ut gjennom fjorder.\n\nDen norske kyststrømmen starter innerst i Skagerrak og følger kysten nordover, hele veien til Barentshavet. Den består av ferskvann fra våre egne og de andre nordeuropeiske elvene, blandet med saltholdig atlanterhavsvann. Det oppstår hele tiden virvler og buktninger i strømmen på grunn av bunnforhold, vær og vind.\n\nHvilke krefter som har størst betydning varierer fra sted til sted. Hvis det blåser kraftig, vil vinden påvirke overflatestrømmene mest. Men hvis det er helt rolige vindforhold og lite avrenning fra nærliggende elver, er det kanskje tidevannsstrømmene som betyr mest."),
        InfoObjects("3", "Hvor salt er egentlig havet?", R.drawable.salinity, "https://havvarsel.no/info/saltholdighet.jpg", "Havene har gjennom millioner av år samlet opp salt fra elvene som igjen har fått det fra berggrunnen. Vi måler saltholdighet i gram salt per kilogram havvann. Du kan, siden det bare er et forholdstall basert på vekt, bruke promille (‰). Vi havforskere bruker ikke enhet i det hele tatt, så ett kilogram havvann med 35 gram salt i seg, har saltholdighet 35.\n\nEn vanlig konsentrasjon i verdenshavene er 35 ‰. Kyststrømmen vår har noe lavere saltholdighet (i gjennomsnitt 34 ‰). Om våren kan badevannet langs sørlandskysten nå ned i 25 ‰. Lenger nord vil det være saltere fordi kyststrømmen blander seg med den salte Atlanterhavsstrømmen – også kjent som Golfstrømmen – på sin vei nordover. Kystvannet er ferskere enn verdenshavene fordi kyststrømmen består av elvevann som renner ut i Nordsjøen, Østersjøen og fra våre egne elver.\n\nSammen med sjøtemperaturen påvirker saltholdigheten vannets egenvekt (tetthet) og dermed hvor godt vi flyter i det. I Dødehavet har saltholdigheten økt til det meste vann kan holde på (cirka 300 ‰), og der flyter du godt oppå overflaten. Det er langt fra slik rundt 35 ‰, og du vil nesten ikke merke forskjellene i saltholdighet på hvor godt du flyter ved ulike badeplasser langs kysten."),
    )
)